#PARAMETER
REGFILEIF_ADDR_W ?=2

#PATHS
REGFILEIF_HW_DIR:=$(REGFILEIF_DIR)/hardware
REGFILEIF_INC_DIR:=$(REGFILEIF_HW_DIR)/include
REGFILEIF_SRC_DIR:=$(REGFILEIF_HW_DIR)/src
REGFILEIF_TB_DIR:=$(REGFILEIF_HW_DIR)/testbench
REGFILEIF_FPGA_DIR:=$(REGFILEIF_HW_DIR)/fpga
REGFILEIF_SUBMODULES_DIR:=$(REGFILEIF_DIR)/submodules

REGFILEIF_SW_DIR:=$(REGFILEIF_DIR)/software

#SUBMODULES
REGFILEIF_SUBMODULES:=MEM INTERCON LIB
$(foreach p, $(REGFILEIF_SUBMODULES), $(eval $p_DIR ?=$(REGFILEIF_SUBMODULES_DIR)/$p))

REMOTE_ROOT_DIR ?=sandbox/iob-regfileif

# defines
DEFINE+=$(defmacro)REGFILEIF_ADDR_W=$(REGFILEIF_ADDR_W)

