	top u0 (
		.clk_clk                                                 (<connected-to-clk_clk>),                                                 //                                     clk.clk
		.ddr3a_status_external_connection_export                 (<connected-to-ddr3a_status_external_connection_export>),                 //        ddr3a_status_external_connection.export
		.ddr3b_status_external_connection_export                 (<connected-to-ddr3b_status_external_connection_export>),                 //        ddr3b_status_external_connection.export
		.hip_ctrl_test_in                                        (<connected-to-hip_ctrl_test_in>),                                        //                                hip_ctrl.test_in
		.hip_ctrl_simu_mode_pipe                                 (<connected-to-hip_ctrl_simu_mode_pipe>),                                 //                                        .simu_mode_pipe
		.hip_pipe_sim_pipe_pclk_in                               (<connected-to-hip_pipe_sim_pipe_pclk_in>),                               //                                hip_pipe.sim_pipe_pclk_in
		.hip_pipe_sim_pipe_rate                                  (<connected-to-hip_pipe_sim_pipe_rate>),                                  //                                        .sim_pipe_rate
		.hip_pipe_sim_ltssmstate                                 (<connected-to-hip_pipe_sim_ltssmstate>),                                 //                                        .sim_ltssmstate
		.hip_pipe_eidleinfersel0                                 (<connected-to-hip_pipe_eidleinfersel0>),                                 //                                        .eidleinfersel0
		.hip_pipe_eidleinfersel1                                 (<connected-to-hip_pipe_eidleinfersel1>),                                 //                                        .eidleinfersel1
		.hip_pipe_eidleinfersel2                                 (<connected-to-hip_pipe_eidleinfersel2>),                                 //                                        .eidleinfersel2
		.hip_pipe_eidleinfersel3                                 (<connected-to-hip_pipe_eidleinfersel3>),                                 //                                        .eidleinfersel3
		.hip_pipe_eidleinfersel4                                 (<connected-to-hip_pipe_eidleinfersel4>),                                 //                                        .eidleinfersel4
		.hip_pipe_eidleinfersel5                                 (<connected-to-hip_pipe_eidleinfersel5>),                                 //                                        .eidleinfersel5
		.hip_pipe_eidleinfersel6                                 (<connected-to-hip_pipe_eidleinfersel6>),                                 //                                        .eidleinfersel6
		.hip_pipe_eidleinfersel7                                 (<connected-to-hip_pipe_eidleinfersel7>),                                 //                                        .eidleinfersel7
		.hip_pipe_powerdown0                                     (<connected-to-hip_pipe_powerdown0>),                                     //                                        .powerdown0
		.hip_pipe_powerdown1                                     (<connected-to-hip_pipe_powerdown1>),                                     //                                        .powerdown1
		.hip_pipe_powerdown2                                     (<connected-to-hip_pipe_powerdown2>),                                     //                                        .powerdown2
		.hip_pipe_powerdown3                                     (<connected-to-hip_pipe_powerdown3>),                                     //                                        .powerdown3
		.hip_pipe_powerdown4                                     (<connected-to-hip_pipe_powerdown4>),                                     //                                        .powerdown4
		.hip_pipe_powerdown5                                     (<connected-to-hip_pipe_powerdown5>),                                     //                                        .powerdown5
		.hip_pipe_powerdown6                                     (<connected-to-hip_pipe_powerdown6>),                                     //                                        .powerdown6
		.hip_pipe_powerdown7                                     (<connected-to-hip_pipe_powerdown7>),                                     //                                        .powerdown7
		.hip_pipe_rxpolarity0                                    (<connected-to-hip_pipe_rxpolarity0>),                                    //                                        .rxpolarity0
		.hip_pipe_rxpolarity1                                    (<connected-to-hip_pipe_rxpolarity1>),                                    //                                        .rxpolarity1
		.hip_pipe_rxpolarity2                                    (<connected-to-hip_pipe_rxpolarity2>),                                    //                                        .rxpolarity2
		.hip_pipe_rxpolarity3                                    (<connected-to-hip_pipe_rxpolarity3>),                                    //                                        .rxpolarity3
		.hip_pipe_rxpolarity4                                    (<connected-to-hip_pipe_rxpolarity4>),                                    //                                        .rxpolarity4
		.hip_pipe_rxpolarity5                                    (<connected-to-hip_pipe_rxpolarity5>),                                    //                                        .rxpolarity5
		.hip_pipe_rxpolarity6                                    (<connected-to-hip_pipe_rxpolarity6>),                                    //                                        .rxpolarity6
		.hip_pipe_rxpolarity7                                    (<connected-to-hip_pipe_rxpolarity7>),                                    //                                        .rxpolarity7
		.hip_pipe_txcompl0                                       (<connected-to-hip_pipe_txcompl0>),                                       //                                        .txcompl0
		.hip_pipe_txcompl1                                       (<connected-to-hip_pipe_txcompl1>),                                       //                                        .txcompl1
		.hip_pipe_txcompl2                                       (<connected-to-hip_pipe_txcompl2>),                                       //                                        .txcompl2
		.hip_pipe_txcompl3                                       (<connected-to-hip_pipe_txcompl3>),                                       //                                        .txcompl3
		.hip_pipe_txcompl4                                       (<connected-to-hip_pipe_txcompl4>),                                       //                                        .txcompl4
		.hip_pipe_txcompl5                                       (<connected-to-hip_pipe_txcompl5>),                                       //                                        .txcompl5
		.hip_pipe_txcompl6                                       (<connected-to-hip_pipe_txcompl6>),                                       //                                        .txcompl6
		.hip_pipe_txcompl7                                       (<connected-to-hip_pipe_txcompl7>),                                       //                                        .txcompl7
		.hip_pipe_txdata0                                        (<connected-to-hip_pipe_txdata0>),                                        //                                        .txdata0
		.hip_pipe_txdata1                                        (<connected-to-hip_pipe_txdata1>),                                        //                                        .txdata1
		.hip_pipe_txdata2                                        (<connected-to-hip_pipe_txdata2>),                                        //                                        .txdata2
		.hip_pipe_txdata3                                        (<connected-to-hip_pipe_txdata3>),                                        //                                        .txdata3
		.hip_pipe_txdata4                                        (<connected-to-hip_pipe_txdata4>),                                        //                                        .txdata4
		.hip_pipe_txdata5                                        (<connected-to-hip_pipe_txdata5>),                                        //                                        .txdata5
		.hip_pipe_txdata6                                        (<connected-to-hip_pipe_txdata6>),                                        //                                        .txdata6
		.hip_pipe_txdata7                                        (<connected-to-hip_pipe_txdata7>),                                        //                                        .txdata7
		.hip_pipe_txdatak0                                       (<connected-to-hip_pipe_txdatak0>),                                       //                                        .txdatak0
		.hip_pipe_txdatak1                                       (<connected-to-hip_pipe_txdatak1>),                                       //                                        .txdatak1
		.hip_pipe_txdatak2                                       (<connected-to-hip_pipe_txdatak2>),                                       //                                        .txdatak2
		.hip_pipe_txdatak3                                       (<connected-to-hip_pipe_txdatak3>),                                       //                                        .txdatak3
		.hip_pipe_txdatak4                                       (<connected-to-hip_pipe_txdatak4>),                                       //                                        .txdatak4
		.hip_pipe_txdatak5                                       (<connected-to-hip_pipe_txdatak5>),                                       //                                        .txdatak5
		.hip_pipe_txdatak6                                       (<connected-to-hip_pipe_txdatak6>),                                       //                                        .txdatak6
		.hip_pipe_txdatak7                                       (<connected-to-hip_pipe_txdatak7>),                                       //                                        .txdatak7
		.hip_pipe_txdetectrx0                                    (<connected-to-hip_pipe_txdetectrx0>),                                    //                                        .txdetectrx0
		.hip_pipe_txdetectrx1                                    (<connected-to-hip_pipe_txdetectrx1>),                                    //                                        .txdetectrx1
		.hip_pipe_txdetectrx2                                    (<connected-to-hip_pipe_txdetectrx2>),                                    //                                        .txdetectrx2
		.hip_pipe_txdetectrx3                                    (<connected-to-hip_pipe_txdetectrx3>),                                    //                                        .txdetectrx3
		.hip_pipe_txdetectrx4                                    (<connected-to-hip_pipe_txdetectrx4>),                                    //                                        .txdetectrx4
		.hip_pipe_txdetectrx5                                    (<connected-to-hip_pipe_txdetectrx5>),                                    //                                        .txdetectrx5
		.hip_pipe_txdetectrx6                                    (<connected-to-hip_pipe_txdetectrx6>),                                    //                                        .txdetectrx6
		.hip_pipe_txdetectrx7                                    (<connected-to-hip_pipe_txdetectrx7>),                                    //                                        .txdetectrx7
		.hip_pipe_txelecidle0                                    (<connected-to-hip_pipe_txelecidle0>),                                    //                                        .txelecidle0
		.hip_pipe_txelecidle1                                    (<connected-to-hip_pipe_txelecidle1>),                                    //                                        .txelecidle1
		.hip_pipe_txelecidle2                                    (<connected-to-hip_pipe_txelecidle2>),                                    //                                        .txelecidle2
		.hip_pipe_txelecidle3                                    (<connected-to-hip_pipe_txelecidle3>),                                    //                                        .txelecidle3
		.hip_pipe_txelecidle4                                    (<connected-to-hip_pipe_txelecidle4>),                                    //                                        .txelecidle4
		.hip_pipe_txelecidle5                                    (<connected-to-hip_pipe_txelecidle5>),                                    //                                        .txelecidle5
		.hip_pipe_txelecidle6                                    (<connected-to-hip_pipe_txelecidle6>),                                    //                                        .txelecidle6
		.hip_pipe_txelecidle7                                    (<connected-to-hip_pipe_txelecidle7>),                                    //                                        .txelecidle7
		.hip_pipe_txdeemph0                                      (<connected-to-hip_pipe_txdeemph0>),                                      //                                        .txdeemph0
		.hip_pipe_txdeemph1                                      (<connected-to-hip_pipe_txdeemph1>),                                      //                                        .txdeemph1
		.hip_pipe_txdeemph2                                      (<connected-to-hip_pipe_txdeemph2>),                                      //                                        .txdeemph2
		.hip_pipe_txdeemph3                                      (<connected-to-hip_pipe_txdeemph3>),                                      //                                        .txdeemph3
		.hip_pipe_txdeemph4                                      (<connected-to-hip_pipe_txdeemph4>),                                      //                                        .txdeemph4
		.hip_pipe_txdeemph5                                      (<connected-to-hip_pipe_txdeemph5>),                                      //                                        .txdeemph5
		.hip_pipe_txdeemph6                                      (<connected-to-hip_pipe_txdeemph6>),                                      //                                        .txdeemph6
		.hip_pipe_txdeemph7                                      (<connected-to-hip_pipe_txdeemph7>),                                      //                                        .txdeemph7
		.hip_pipe_txmargin0                                      (<connected-to-hip_pipe_txmargin0>),                                      //                                        .txmargin0
		.hip_pipe_txmargin1                                      (<connected-to-hip_pipe_txmargin1>),                                      //                                        .txmargin1
		.hip_pipe_txmargin2                                      (<connected-to-hip_pipe_txmargin2>),                                      //                                        .txmargin2
		.hip_pipe_txmargin3                                      (<connected-to-hip_pipe_txmargin3>),                                      //                                        .txmargin3
		.hip_pipe_txmargin4                                      (<connected-to-hip_pipe_txmargin4>),                                      //                                        .txmargin4
		.hip_pipe_txmargin5                                      (<connected-to-hip_pipe_txmargin5>),                                      //                                        .txmargin5
		.hip_pipe_txmargin6                                      (<connected-to-hip_pipe_txmargin6>),                                      //                                        .txmargin6
		.hip_pipe_txmargin7                                      (<connected-to-hip_pipe_txmargin7>),                                      //                                        .txmargin7
		.hip_pipe_txswing0                                       (<connected-to-hip_pipe_txswing0>),                                       //                                        .txswing0
		.hip_pipe_txswing1                                       (<connected-to-hip_pipe_txswing1>),                                       //                                        .txswing1
		.hip_pipe_txswing2                                       (<connected-to-hip_pipe_txswing2>),                                       //                                        .txswing2
		.hip_pipe_txswing3                                       (<connected-to-hip_pipe_txswing3>),                                       //                                        .txswing3
		.hip_pipe_txswing4                                       (<connected-to-hip_pipe_txswing4>),                                       //                                        .txswing4
		.hip_pipe_txswing5                                       (<connected-to-hip_pipe_txswing5>),                                       //                                        .txswing5
		.hip_pipe_txswing6                                       (<connected-to-hip_pipe_txswing6>),                                       //                                        .txswing6
		.hip_pipe_txswing7                                       (<connected-to-hip_pipe_txswing7>),                                       //                                        .txswing7
		.hip_pipe_phystatus0                                     (<connected-to-hip_pipe_phystatus0>),                                     //                                        .phystatus0
		.hip_pipe_phystatus1                                     (<connected-to-hip_pipe_phystatus1>),                                     //                                        .phystatus1
		.hip_pipe_phystatus2                                     (<connected-to-hip_pipe_phystatus2>),                                     //                                        .phystatus2
		.hip_pipe_phystatus3                                     (<connected-to-hip_pipe_phystatus3>),                                     //                                        .phystatus3
		.hip_pipe_phystatus4                                     (<connected-to-hip_pipe_phystatus4>),                                     //                                        .phystatus4
		.hip_pipe_phystatus5                                     (<connected-to-hip_pipe_phystatus5>),                                     //                                        .phystatus5
		.hip_pipe_phystatus6                                     (<connected-to-hip_pipe_phystatus6>),                                     //                                        .phystatus6
		.hip_pipe_phystatus7                                     (<connected-to-hip_pipe_phystatus7>),                                     //                                        .phystatus7
		.hip_pipe_rxdata0                                        (<connected-to-hip_pipe_rxdata0>),                                        //                                        .rxdata0
		.hip_pipe_rxdata1                                        (<connected-to-hip_pipe_rxdata1>),                                        //                                        .rxdata1
		.hip_pipe_rxdata2                                        (<connected-to-hip_pipe_rxdata2>),                                        //                                        .rxdata2
		.hip_pipe_rxdata3                                        (<connected-to-hip_pipe_rxdata3>),                                        //                                        .rxdata3
		.hip_pipe_rxdata4                                        (<connected-to-hip_pipe_rxdata4>),                                        //                                        .rxdata4
		.hip_pipe_rxdata5                                        (<connected-to-hip_pipe_rxdata5>),                                        //                                        .rxdata5
		.hip_pipe_rxdata6                                        (<connected-to-hip_pipe_rxdata6>),                                        //                                        .rxdata6
		.hip_pipe_rxdata7                                        (<connected-to-hip_pipe_rxdata7>),                                        //                                        .rxdata7
		.hip_pipe_rxdatak0                                       (<connected-to-hip_pipe_rxdatak0>),                                       //                                        .rxdatak0
		.hip_pipe_rxdatak1                                       (<connected-to-hip_pipe_rxdatak1>),                                       //                                        .rxdatak1
		.hip_pipe_rxdatak2                                       (<connected-to-hip_pipe_rxdatak2>),                                       //                                        .rxdatak2
		.hip_pipe_rxdatak3                                       (<connected-to-hip_pipe_rxdatak3>),                                       //                                        .rxdatak3
		.hip_pipe_rxdatak4                                       (<connected-to-hip_pipe_rxdatak4>),                                       //                                        .rxdatak4
		.hip_pipe_rxdatak5                                       (<connected-to-hip_pipe_rxdatak5>),                                       //                                        .rxdatak5
		.hip_pipe_rxdatak6                                       (<connected-to-hip_pipe_rxdatak6>),                                       //                                        .rxdatak6
		.hip_pipe_rxdatak7                                       (<connected-to-hip_pipe_rxdatak7>),                                       //                                        .rxdatak7
		.hip_pipe_rxelecidle0                                    (<connected-to-hip_pipe_rxelecidle0>),                                    //                                        .rxelecidle0
		.hip_pipe_rxelecidle1                                    (<connected-to-hip_pipe_rxelecidle1>),                                    //                                        .rxelecidle1
		.hip_pipe_rxelecidle2                                    (<connected-to-hip_pipe_rxelecidle2>),                                    //                                        .rxelecidle2
		.hip_pipe_rxelecidle3                                    (<connected-to-hip_pipe_rxelecidle3>),                                    //                                        .rxelecidle3
		.hip_pipe_rxelecidle4                                    (<connected-to-hip_pipe_rxelecidle4>),                                    //                                        .rxelecidle4
		.hip_pipe_rxelecidle5                                    (<connected-to-hip_pipe_rxelecidle5>),                                    //                                        .rxelecidle5
		.hip_pipe_rxelecidle6                                    (<connected-to-hip_pipe_rxelecidle6>),                                    //                                        .rxelecidle6
		.hip_pipe_rxelecidle7                                    (<connected-to-hip_pipe_rxelecidle7>),                                    //                                        .rxelecidle7
		.hip_pipe_rxstatus0                                      (<connected-to-hip_pipe_rxstatus0>),                                      //                                        .rxstatus0
		.hip_pipe_rxstatus1                                      (<connected-to-hip_pipe_rxstatus1>),                                      //                                        .rxstatus1
		.hip_pipe_rxstatus2                                      (<connected-to-hip_pipe_rxstatus2>),                                      //                                        .rxstatus2
		.hip_pipe_rxstatus3                                      (<connected-to-hip_pipe_rxstatus3>),                                      //                                        .rxstatus3
		.hip_pipe_rxstatus4                                      (<connected-to-hip_pipe_rxstatus4>),                                      //                                        .rxstatus4
		.hip_pipe_rxstatus5                                      (<connected-to-hip_pipe_rxstatus5>),                                      //                                        .rxstatus5
		.hip_pipe_rxstatus6                                      (<connected-to-hip_pipe_rxstatus6>),                                      //                                        .rxstatus6
		.hip_pipe_rxstatus7                                      (<connected-to-hip_pipe_rxstatus7>),                                      //                                        .rxstatus7
		.hip_pipe_rxvalid0                                       (<connected-to-hip_pipe_rxvalid0>),                                       //                                        .rxvalid0
		.hip_pipe_rxvalid1                                       (<connected-to-hip_pipe_rxvalid1>),                                       //                                        .rxvalid1
		.hip_pipe_rxvalid2                                       (<connected-to-hip_pipe_rxvalid2>),                                       //                                        .rxvalid2
		.hip_pipe_rxvalid3                                       (<connected-to-hip_pipe_rxvalid3>),                                       //                                        .rxvalid3
		.hip_pipe_rxvalid4                                       (<connected-to-hip_pipe_rxvalid4>),                                       //                                        .rxvalid4
		.hip_pipe_rxvalid5                                       (<connected-to-hip_pipe_rxvalid5>),                                       //                                        .rxvalid5
		.hip_pipe_rxvalid6                                       (<connected-to-hip_pipe_rxvalid6>),                                       //                                        .rxvalid6
		.hip_pipe_rxvalid7                                       (<connected-to-hip_pipe_rxvalid7>),                                       //                                        .rxvalid7
		.hip_serial_rx_in0                                       (<connected-to-hip_serial_rx_in0>),                                       //                              hip_serial.rx_in0
		.hip_serial_rx_in1                                       (<connected-to-hip_serial_rx_in1>),                                       //                                        .rx_in1
		.hip_serial_rx_in2                                       (<connected-to-hip_serial_rx_in2>),                                       //                                        .rx_in2
		.hip_serial_rx_in3                                       (<connected-to-hip_serial_rx_in3>),                                       //                                        .rx_in3
		.hip_serial_rx_in4                                       (<connected-to-hip_serial_rx_in4>),                                       //                                        .rx_in4
		.hip_serial_rx_in5                                       (<connected-to-hip_serial_rx_in5>),                                       //                                        .rx_in5
		.hip_serial_rx_in6                                       (<connected-to-hip_serial_rx_in6>),                                       //                                        .rx_in6
		.hip_serial_rx_in7                                       (<connected-to-hip_serial_rx_in7>),                                       //                                        .rx_in7
		.hip_serial_tx_out0                                      (<connected-to-hip_serial_tx_out0>),                                      //                                        .tx_out0
		.hip_serial_tx_out1                                      (<connected-to-hip_serial_tx_out1>),                                      //                                        .tx_out1
		.hip_serial_tx_out2                                      (<connected-to-hip_serial_tx_out2>),                                      //                                        .tx_out2
		.hip_serial_tx_out3                                      (<connected-to-hip_serial_tx_out3>),                                      //                                        .tx_out3
		.hip_serial_tx_out4                                      (<connected-to-hip_serial_tx_out4>),                                      //                                        .tx_out4
		.hip_serial_tx_out5                                      (<connected-to-hip_serial_tx_out5>),                                      //                                        .tx_out5
		.hip_serial_tx_out6                                      (<connected-to-hip_serial_tx_out6>),                                      //                                        .tx_out6
		.hip_serial_tx_out7                                      (<connected-to-hip_serial_tx_out7>),                                      //                                        .tx_out7
		.mem_if_ddr3a_mem_mem_a                                  (<connected-to-mem_if_ddr3a_mem_mem_a>),                                  //                        mem_if_ddr3a_mem.mem_a
		.mem_if_ddr3a_mem_mem_ba                                 (<connected-to-mem_if_ddr3a_mem_mem_ba>),                                 //                                        .mem_ba
		.mem_if_ddr3a_mem_mem_ck                                 (<connected-to-mem_if_ddr3a_mem_mem_ck>),                                 //                                        .mem_ck
		.mem_if_ddr3a_mem_mem_ck_n                               (<connected-to-mem_if_ddr3a_mem_mem_ck_n>),                               //                                        .mem_ck_n
		.mem_if_ddr3a_mem_mem_cke                                (<connected-to-mem_if_ddr3a_mem_mem_cke>),                                //                                        .mem_cke
		.mem_if_ddr3a_mem_mem_cs_n                               (<connected-to-mem_if_ddr3a_mem_mem_cs_n>),                               //                                        .mem_cs_n
		.mem_if_ddr3a_mem_mem_dm                                 (<connected-to-mem_if_ddr3a_mem_mem_dm>),                                 //                                        .mem_dm
		.mem_if_ddr3a_mem_mem_ras_n                              (<connected-to-mem_if_ddr3a_mem_mem_ras_n>),                              //                                        .mem_ras_n
		.mem_if_ddr3a_mem_mem_cas_n                              (<connected-to-mem_if_ddr3a_mem_mem_cas_n>),                              //                                        .mem_cas_n
		.mem_if_ddr3a_mem_mem_we_n                               (<connected-to-mem_if_ddr3a_mem_mem_we_n>),                               //                                        .mem_we_n
		.mem_if_ddr3a_mem_mem_reset_n                            (<connected-to-mem_if_ddr3a_mem_mem_reset_n>),                            //                                        .mem_reset_n
		.mem_if_ddr3a_mem_mem_dq                                 (<connected-to-mem_if_ddr3a_mem_mem_dq>),                                 //                                        .mem_dq
		.mem_if_ddr3a_mem_mem_dqs                                (<connected-to-mem_if_ddr3a_mem_mem_dqs>),                                //                                        .mem_dqs
		.mem_if_ddr3a_mem_mem_dqs_n                              (<connected-to-mem_if_ddr3a_mem_mem_dqs_n>),                              //                                        .mem_dqs_n
		.mem_if_ddr3a_mem_mem_odt                                (<connected-to-mem_if_ddr3a_mem_mem_odt>),                                //                                        .mem_odt
		.mem_if_ddr3a_oct_rzqin                                  (<connected-to-mem_if_ddr3a_oct_rzqin>),                                  //                        mem_if_ddr3a_oct.rzqin
		.mem_if_ddr3a_pll_ref_clk_clk                            (<connected-to-mem_if_ddr3a_pll_ref_clk_clk>),                            //                mem_if_ddr3a_pll_ref_clk.clk
		.mem_if_ddr3a_status_local_init_done                     (<connected-to-mem_if_ddr3a_status_local_init_done>),                     //                     mem_if_ddr3a_status.local_init_done
		.mem_if_ddr3a_status_local_cal_success                   (<connected-to-mem_if_ddr3a_status_local_cal_success>),                   //                                        .local_cal_success
		.mem_if_ddr3a_status_local_cal_fail                      (<connected-to-mem_if_ddr3a_status_local_cal_fail>),                      //                                        .local_cal_fail
		.mem_if_ddr3b_mem_mem_a                                  (<connected-to-mem_if_ddr3b_mem_mem_a>),                                  //                        mem_if_ddr3b_mem.mem_a
		.mem_if_ddr3b_mem_mem_ba                                 (<connected-to-mem_if_ddr3b_mem_mem_ba>),                                 //                                        .mem_ba
		.mem_if_ddr3b_mem_mem_ck                                 (<connected-to-mem_if_ddr3b_mem_mem_ck>),                                 //                                        .mem_ck
		.mem_if_ddr3b_mem_mem_ck_n                               (<connected-to-mem_if_ddr3b_mem_mem_ck_n>),                               //                                        .mem_ck_n
		.mem_if_ddr3b_mem_mem_cke                                (<connected-to-mem_if_ddr3b_mem_mem_cke>),                                //                                        .mem_cke
		.mem_if_ddr3b_mem_mem_cs_n                               (<connected-to-mem_if_ddr3b_mem_mem_cs_n>),                               //                                        .mem_cs_n
		.mem_if_ddr3b_mem_mem_dm                                 (<connected-to-mem_if_ddr3b_mem_mem_dm>),                                 //                                        .mem_dm
		.mem_if_ddr3b_mem_mem_ras_n                              (<connected-to-mem_if_ddr3b_mem_mem_ras_n>),                              //                                        .mem_ras_n
		.mem_if_ddr3b_mem_mem_cas_n                              (<connected-to-mem_if_ddr3b_mem_mem_cas_n>),                              //                                        .mem_cas_n
		.mem_if_ddr3b_mem_mem_we_n                               (<connected-to-mem_if_ddr3b_mem_mem_we_n>),                               //                                        .mem_we_n
		.mem_if_ddr3b_mem_mem_reset_n                            (<connected-to-mem_if_ddr3b_mem_mem_reset_n>),                            //                                        .mem_reset_n
		.mem_if_ddr3b_mem_mem_dq                                 (<connected-to-mem_if_ddr3b_mem_mem_dq>),                                 //                                        .mem_dq
		.mem_if_ddr3b_mem_mem_dqs                                (<connected-to-mem_if_ddr3b_mem_mem_dqs>),                                //                                        .mem_dqs
		.mem_if_ddr3b_mem_mem_dqs_n                              (<connected-to-mem_if_ddr3b_mem_mem_dqs_n>),                              //                                        .mem_dqs_n
		.mem_if_ddr3b_mem_mem_odt                                (<connected-to-mem_if_ddr3b_mem_mem_odt>),                                //                                        .mem_odt
		.mem_if_ddr3b_oct_rzqin                                  (<connected-to-mem_if_ddr3b_oct_rzqin>),                                  //                        mem_if_ddr3b_oct.rzqin
		.mem_if_ddr3b_pll_ref_clk_clk                            (<connected-to-mem_if_ddr3b_pll_ref_clk_clk>),                            //                mem_if_ddr3b_pll_ref_clk.clk
		.mem_if_ddr3b_status_local_init_done                     (<connected-to-mem_if_ddr3b_status_local_init_done>),                     //                     mem_if_ddr3b_status.local_init_done
		.mem_if_ddr3b_status_local_cal_success                   (<connected-to-mem_if_ddr3b_status_local_cal_success>),                   //                                        .local_cal_success
		.mem_if_ddr3b_status_local_cal_fail                      (<connected-to-mem_if_ddr3b_status_local_cal_fail>),                      //                                        .local_cal_fail
		.pcie_256_hip_avmm_0_reconfig_clk_locked_fixedclk_locked (<connected-to-pcie_256_hip_avmm_0_reconfig_clk_locked_fixedclk_locked>), // pcie_256_hip_avmm_0_reconfig_clk_locked.fixedclk_locked
		.pcie_rstn_npor                                          (<connected-to-pcie_rstn_npor>),                                          //                               pcie_rstn.npor
		.pcie_rstn_pin_perst                                     (<connected-to-pcie_rstn_pin_perst>),                                     //                                        .pin_perst
		.pio_button_external_connection_export                   (<connected-to-pio_button_external_connection_export>),                   //          pio_button_external_connection.export
		.pio_led_external_connection_export                      (<connected-to-pio_led_external_connection_export>),                      //             pio_led_external_connection.export
		.refclk_clk                                              (<connected-to-refclk_clk>),                                              //                                  refclk.clk
		.reset_reset_n                                           (<connected-to-reset_reset_n>)                                            //                                   reset.reset_n
	);

