#!/bin/env python3

# importing modules
import os
import sys
import importlib.util
import time
import curses.ascii

package_name = 'serial'
spec = importlib.util.find_spec(package_name)
if spec is None:
    print("IOb-Console: ERROR... py{0} is not installed!".format(package_name))
    exit()
import serial

# Global variables
SerialFlag = True
mode = 0o600
PROGNAME = "IOb-Console"
EOT = b'\x04' # End of Transmission in Hexadecimal
ENQ = b'\x05' # Enquiry in Hexadecimal
ACK = b'\x06' # Acknowledgement in Hexadecimal
FTX = b'\x07' # Receive file request
FRX = b'\x08' # Send file request

try:
    open('./cnsl2soc',"x")
except IOError as e:
    print('Error creating new cnsl2soc file!')
try:
    open('./soc2cnsl',"x")
except IOError as e:
    print('Error creating new soc2cnsl file!')

def tb_write(data):
    f = open('./cnsl2soc', "wb")
    f.write(data)
    f.close()

def tb_read_until(end = b'\x00'):
    data = b''
    if (os.path.exists('./soc2cnsl')):
        f = open('./soc2cnsl', "rb+")
        while(True):
            byte = f.read(1)
            data += byte
            #print('Read: "{0}"'.format(data))
            if (byte == end):
                f.seek(0) # absolute file positioning
                f.truncate() # to erase all data
                f.close()
                return data

def tb_read(number_of_bytes = 1):
    data = b''
    # print(number_of_bytes)
    if (os.path.exists('./soc2cnsl')):
        f = open('./soc2cnsl', "rb+")
        data = f.read(number_of_bytes)
        if(data!=b''):
            f.seek(0) # absolute file positioning
            f.truncate() # to erase all data
        f.close()
    return data
# configure the serial connections (the parameters differs on the device you are connecting to)

ser = serial.Serial()
ser.port = "/dev/ttyUSB0"
ser.baudrate = 115200
ser.bytesize = serial.EIGHTBITS #number of bits per bytes
ser.parity = serial.PARITY_NONE #set parity check: no parity
ser.stopbits = serial.STOPBITS_ONE #number of stop bits
#ser.timeout = None          #block read
#ser.timeout = 1            #non-block read
ser.timeout = 2              #timeout block read
ser.xonxoff = False     #disable software flow control
ser.rtscts = False     #disable hardware (RTS/CTS) flow control
ser.dsrdtr = False       #disable hardware (DSR/DTR) flow control
ser.writeTimeout = 2     #timeout for write


# Print ERROR
def cnsl_perror(mesg):
    print(PROGNAME, end = '')
    print(": " + str(mesg))
    exit(1)

# Receive file name
def cnsl_recvstr():
    if SerialFlag:
        name = ser.read_until(b'\x00') # reads 80 bytes
    else:
        name = tb_read_until(b'\x00')
    print(PROGNAME, end = '')
    print(': file name {0} '.format(name))
    sys.stdout.flush()
    return name

# Send file to target
def cnsl_sendfile():
    file_size = 0
    name = b''
    # receive file name
    name = cnsl_recvstr()[:-1]
    # open file to send
    # print(name)
    f = open(name, 'rb')
    file_size = os.path.getsize(name)
    if SerialFlag:
        ser.write(file_size.to_bytes(4,  byteorder='little')) #send file size
        ser.write(f.read()) #send file
    else:
        tb_write(file_size.to_bytes(4,  byteorder='little'))
        tb_write(f.read())
    f.close()
    print(PROGNAME, end = '')
    print(': file of size {0} bytes'.format(file_size))
    print(PROGNAME, end = '')
    print(': file sent')

def cnsl_recvfile():
    file_size = 0
    name = ""
    # receive file name
    name = cnsl_recvstr()[:-1]
    # open data file
    f = open(name, 'wb')
    if SerialFlag:
        aux = ser.read(4)
        file_size = int.from_bytes(aux, byteorder='little', signed=False)
        print(PROGNAME, end = ' ')
        print(': file size: {0} bytes'.format(file_size))
        data = ser.read(file_size)
    else:
        file_size = int.from_bytes(tb_read(4), byteorder='little', signed=False)
        print(PROGNAME, end = ' ')
        print(': file size: {0} bytes'.format(file_size))
        data = tb_read(file_size)
    # print(data)
    f.write(data)
    f.close()
    print(PROGNAME, end = '')
    print(': file of size {0} bytes received'.format(file_size))

def usage(message):
    cnsl_perror("usage: ./console -s <serial port> [ -f ] [ -L/--local ]")
    cnsl_perror(message)

def clean_exit():
    if SerialFlag:
        ser.close()
    os.remove('./cnsl2soc')
    os.remove('./soc2cnsl')
    exit(0)

def init_print():
    print()
    print('+-----------------------------------------------+')
    print('|                   IOb-Console                 |')
    print('+-----------------------------------------------+')
    print()
    if SerialFlag:
        print('  BaudRate = {0}'.format(ser.baudrate))
        print('  StopBits = {0}'.format(ser.stopbits))
        print('  Parity   = None')
        print()
    print(PROGNAME, end = '')
    print(': connecting...')
    print()


# Main function.
def main():
    global SerialFlag
    load_fw = False
    gotENQ = False
    byte = b'\x00'
    if ('-L' in sys.argv or '--local' in sys.argv):
        SerialFlag = False
    elif ('-s' in sys.argv):
        if (len(sys.argv)<3):
            usage("PROGNAME: not enough program arguments")
        # open connection
        try:
            ser.port = sys.argv[sys.argv.index('-s')+1]
            ser.open()
        except Exception:
            usage("Error open serial port.")
    else:
        usage("PROGNAME: not enough program arguments")
    if ('-f' in sys.argv):
        load_fw = True
    init_print()
    # Reading the data from the serial port or FIFO files. This will be running in an infinite loop.
    while(True):
        # get byte from target
        if (not SerialFlag):
            byte = tb_read()
        elif (ser.isOpen()):
            byte = ser.read()
        # process command
        if (byte == ENQ):
            if (not gotENQ):
                gotENQ = True
                if (load_fw):
                    if SerialFlag:
                        ser.write(FRX)
                    else:
                        tb_write(FRX)
                else:
                    if SerialFlag:
                        ser.write(ACK)
                    else:
                        tb_write(ACK)

        elif (byte == EOT):
            print(PROGNAME, end = '')
            print(': exiting...')
            clean_exit()
        elif (byte == FTX):
            print(PROGNAME, end = '')
            print(': got file receive request')
            cnsl_recvfile()
        elif (byte == FRX):
            print(PROGNAME, end = '')
            print(': got file send request')
            cnsl_sendfile()
        else:
            print(str(byte, 'ascii'), end = '')
            sys.stdout.flush()

if __name__ == "__main__":
    main()
