ROOT_DIR:=../../../..

BOARD=COLORLIGHT_I5

#TODO
BOARD_SERVER=$(I5_SERVER)
BOARD_USER=$(I5_USER)

DEVICE=LFE5U-25F-6BG381C

#specify any conditions that prevent running this FPGA
NORUN = 0

FREQ=25000000 #25MHz

include ../colorlight.mk


