ROOT_DIR:=../../../..

BOARD=COLORLIGHT_I5

#TODO
BOARD_SERVER=$(DE10_SERVER)
BOARD_USER=$(DE10_USER)

#depends on revision
DEVICE=123

#TODO?: specify any conditions that prevent running this FPGA
NORUN = 0

FREQ=25000000 #25MHz

include ../colorlight.mk


