ROOT_DIR:=../../../..

BOARD=DE10-LITE

BOARD_SERVER=$(DE10_SERVER)
BOARD_USER=$(DE10_USER)


#specify any conditions that prevent running this FPGA
NORUN = $(USE_DDR)

FREQ=50000000

include ../quartus.mk
