# SPDX-FileCopyrightText: 2024 IObundle
#
# SPDX-License-Identifier: MIT

## DDR4 Interface
set_property PACKAGE_PIN AA25 [get_ports {c0_ddr4_ck_t_o}]
set_property PACKAGE_PIN AB25 [get_ports {c0_ddr4_ck_c_o}]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports {c0_ddr4_ck_t_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ck_t_o} ]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports {c0_ddr4_ck_c_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ck_c_o} ]

set_property PACKAGE_PIN AA24 [get_ports {c0_ddr4_adr_o[0]}]
set_property PACKAGE_PIN AB24 [get_ports {c0_ddr4_adr_o[1]}]
set_property PACKAGE_PIN AB26 [get_ports {c0_ddr4_adr_o[2]}]
set_property PACKAGE_PIN AC26 [get_ports {c0_ddr4_adr_o[3]}]
set_property PACKAGE_PIN AA22 [get_ports {c0_ddr4_adr_o[4]}]
set_property PACKAGE_PIN AB22 [get_ports {c0_ddr4_adr_o[5]}]
set_property PACKAGE_PIN Y23 [get_ports {c0_ddr4_adr_o[6]}]
set_property PACKAGE_PIN AA23 [get_ports {c0_ddr4_adr_o[7]}]
set_property PACKAGE_PIN AC23 [get_ports {c0_ddr4_adr_o[8]}]
set_property PACKAGE_PIN AC24 [get_ports {c0_ddr4_adr_o[9]}]
set_property PACKAGE_PIN W23 [get_ports {c0_ddr4_adr_o[10]}]
set_property PACKAGE_PIN W24 [get_ports {c0_ddr4_adr_o[11]}]
set_property PACKAGE_PIN W25 [get_ports {c0_ddr4_adr_o[12]}]
set_property PACKAGE_PIN W26 [get_ports {c0_ddr4_adr_o[13]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[13]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[13]}]

set_property PACKAGE_PIN F22 [get_ports {c0_ddr4_dqs_t_io[3]}]
set_property PACKAGE_PIN F23 [get_ports {c0_ddr4_dqs_c_io[3]}]
set_property PACKAGE_PIN K26 [get_ports {c0_ddr4_dqs_t_io[2]}]
set_property PACKAGE_PIN J26 [get_ports {c0_ddr4_dqs_c_io[2]}]
set_property PACKAGE_PIN T19 [get_ports {c0_ddr4_dqs_t_io[1]}]
set_property PACKAGE_PIN T20 [get_ports {c0_ddr4_dqs_c_io[1]}]
set_property PACKAGE_PIN R22 [get_ports {c0_ddr4_dqs_t_io[0]}]
set_property PACKAGE_PIN R23 [get_ports {c0_ddr4_dqs_c_io[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_t_io[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_c_io[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_t_io[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_c_io[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_t_io[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_c_io[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_t_io[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_c_io[0]}]

set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t_io[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c_io[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t_io[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c_io[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t_io[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c_io[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t_io[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c_io[0]}]

set_property PACKAGE_PIN E25 [get_ports {c0_ddr4_dm_dbi_n_io[3]}]
set_property PACKAGE_PIN N23 [get_ports {c0_ddr4_dm_dbi_n_io[2]}]
set_property PACKAGE_PIN R18 [get_ports {c0_ddr4_dm_dbi_n_io[1]}]
set_property PACKAGE_PIN T23 [get_ports {c0_ddr4_dm_dbi_n_io[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dm_dbi_n_io[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dm_dbi_n_io[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dm_dbi_n_io[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dm_dbi_n_io[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n_io[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n_io[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n_io[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n_io[0]}]

set_property PACKAGE_PIN G24 [get_ports {c0_ddr4_dq_io[31]}]
set_property PACKAGE_PIN H24 [get_ports {c0_ddr4_dq_io[30]}]
set_property PACKAGE_PIN J25 [get_ports {c0_ddr4_dq_io[29]}]
set_property PACKAGE_PIN J24 [get_ports {c0_ddr4_dq_io[28]}]
set_property PACKAGE_PIN F25 [get_ports {c0_ddr4_dq_io[27]}]
set_property PACKAGE_PIN G25 [get_ports {c0_ddr4_dq_io[26]}]
set_property PACKAGE_PIN G26 [get_ports {c0_ddr4_dq_io[25]}]
set_property PACKAGE_PIN H26 [get_ports {c0_ddr4_dq_io[24]}]
set_property PACKAGE_PIN L25 [get_ports {c0_ddr4_dq_io[23]}]
set_property PACKAGE_PIN M25 [get_ports {c0_ddr4_dq_io[22]}]
set_property PACKAGE_PIN M22 [get_ports {c0_ddr4_dq_io[21]}]
set_property PACKAGE_PIN N22 [get_ports {c0_ddr4_dq_io[20]}]
set_property PACKAGE_PIN L24 [get_ports {c0_ddr4_dq_io[19]}]
set_property PACKAGE_PIN M24 [get_ports {c0_ddr4_dq_io[18]}]
set_property PACKAGE_PIN M26 [get_ports {c0_ddr4_dq_io[17]}]
set_property PACKAGE_PIN N26 [get_ports {c0_ddr4_dq_io[16]}]
set_property PACKAGE_PIN U21 [get_ports {c0_ddr4_dq_io[15]}]
set_property PACKAGE_PIN U20 [get_ports {c0_ddr4_dq_io[14]}]
set_property PACKAGE_PIN R20 [get_ports {c0_ddr4_dq_io[13]}]
set_property PACKAGE_PIN P20 [get_ports {c0_ddr4_dq_io[12]}]
set_property PACKAGE_PIN P19 [get_ports {c0_ddr4_dq_io[11]}]
set_property PACKAGE_PIN P18 [get_ports {c0_ddr4_dq_io[10]}]
set_property PACKAGE_PIN R21 [get_ports {c0_ddr4_dq_io[9]}]
set_property PACKAGE_PIN P21 [get_ports {c0_ddr4_dq_io[8]}]
set_property PACKAGE_PIN R25 [get_ports {c0_ddr4_dq_io[7]}]
set_property PACKAGE_PIN P25 [get_ports {c0_ddr4_dq_io[6]}]
set_property PACKAGE_PIN P24 [get_ports {c0_ddr4_dq_io[5]}]
set_property PACKAGE_PIN P23 [get_ports {c0_ddr4_dq_io[4]}]
set_property PACKAGE_PIN R26 [get_ports {c0_ddr4_dq_io[3]}]
set_property PACKAGE_PIN P26 [get_ports {c0_ddr4_dq_io[2]}]
set_property PACKAGE_PIN U22 [get_ports {c0_ddr4_dq_io[1]}]
set_property PACKAGE_PIN T22 [get_ports {c0_ddr4_dq_io[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[31]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[30]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[29]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[28]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[27]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[26]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[25]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[24]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[23]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[22]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[21]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[20]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[19]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[18]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[17]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[16]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq_io[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[31]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[30]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[29]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[28]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[27]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[26]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[25]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[24]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[23]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[22]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[21]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[20]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[19]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[18]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[17]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[16]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq_io[0]}]

## WE_N Signal
set_property PACKAGE_PIN Y25 [get_ports {c0_ddr4_adr_o[14]}]
## CAS_N Signal
set_property PACKAGE_PIN Y26 [get_ports {c0_ddr4_adr_o[15]}]
## RAS_N Signal
set_property PACKAGE_PIN U26 [get_ports {c0_ddr4_adr_o[16]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr_o[16]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr_o[16]}]

set_property PACKAGE_PIN T24 [get_ports {c0_ddr4_act_n_o}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_act_n_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_act_n_o} ]

set_property PACKAGE_PIN T25 [get_ports c0_ddr4_reset_n_o]
set_property IOSTANDARD LVCMOS12 [ get_ports {c0_ddr4_reset_n_o} ]
set_property DRIVE 8 [get_ports c0_ddr4_reset_n_o]

set_property PACKAGE_PIN U25 [get_ports {c0_ddr4_odt_o}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_odt_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_odt_o} ]

set_property PACKAGE_PIN V22 [get_ports {c0_ddr4_cs_n_o}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_cs_n_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_cs_n_o} ]

set_property PACKAGE_PIN V23 [get_ports {c0_ddr4_cke_o}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_cke_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_cke_o} ]

set_property PACKAGE_PIN V26 [get_ports {c0_ddr4_ba_o[0]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_ba_o[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ba_o[0]} ]

set_property PACKAGE_PIN U24 [get_ports {c0_ddr4_ba_o[1]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_ba_o[1]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ba_o[1]} ]

set_property PACKAGE_PIN V24 [get_ports {c0_ddr4_bg_o}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_bg_o} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_bg_o} ]

