#
# Makefile for compiling the documentation.
# Tested with the texlive-full Linux package
#

all:
	make -C presentation all
	make -C pb all

clean:
	make -C presentation clean
	make -C pb clean

clean-all:
	make -C presentation clean-all
	make -C pb clean-all


.PHONY: all clean clean-all
