ROOT_DIR:=../../../..

BOARD=COLORLIGHT_5A-75E

#TODO
BOARD_SERVER=$(5A-75E_SERVER)
BOARD_USER=$(5A-75E_USER)

#ECP5
DEVICE=LFE5U-25F-6BG256C

#specify any conditions that prevent running this FPGA
NORUN = 0

FREQ=25000000 #25MHz

include ../colorlight.mk


