ROOT_DIR:=../../../..

BOARD_SERVER=$(CYC5_SERVER)
BOARD_USER=$(CYC5_USER)

DEVICE=5CGTFD9E5F35C7

#DEFINES
DEFINE+=$(defmacro)IS_CYCLONEV

#DDR controller address width
DDR_ADDR_W=30

#specify any conditions that prevent running this FPGA
#NORUN = $(USE_DDR)
NORUN = 0

FREQ=50000000


include ../quartus.mk


