ROOT_DIR:=../../../..
DEFINE+=$(defmacro)IS_CYCLONEV=1

BOARD=CYCLONEV-GT-DK

BOARD_SERVER=$(CYC5_SERVER)
BOARD_USER=$(CYC5_USER)

#specify any conditions that prevent running this FPGA
NORUN = $(USE_DDR)

include ../quartus.mk


