def _auto_add_settings(cls):
    """Auto-add settings like macros and submodules to the module"""

    # Auto-add VERSION macro if there are software registers
    if cls.regs:
        found_version_macro = False
        if cls.confs:
            for macro in cls.confs:
                if macro["name"] == "VERSION":
                    found_version_macro = True
        if not found_version_macro:
            cls.confs.append(
                {
                    "name": "VERSION",
                    "type": "M",
                    "val": "16'h" + copy_srcs.version_str_to_digits(cls.version),
                    "min": "NA",
                    "max": "NA",
                    "descr": "Product version. This 16-bit macro uses nibbles to represent decimal numbers using their binary values. The two most significant nibbles represent the integral part of the version, and the two least significant nibbles represent the decimal part. For example V12.34 is represented by 0x1234.",
                }
            )

    if cls.regs:
        # Auto-add iob_ctls module, except if use_netlist
        if cls.name != "iob_ctls" and not cls.use_netlist:
            from iob_ctls import iob_ctls

            iob_ctls.__setup(purpose=cls.get_setup_purpose())
        ## Auto-add iob_s_port.vh
        cls.__generate({"interface": "iob_s_port"}, purpose=cls.get_setup_purpose())
        ## Auto-add iob_s_portmap.vh
        cls.__generate(
            {"interface": "iob_s_s_portmap"}, purpose=cls.get_setup_purpose()
        )


def _build_regs_table(cls):
    """Build registers table.
    :returns csr_gen csr_gen_obj: Instance of csr_gen class
    :returns list reg_table: Register table generated by `get_reg_table` method of `csr_gen_obj`
    """
    # Don't create regs table if module does not have regs
    if not cls.regs:
        return None, None

    # Make sure 'general' registers table exists
    general_regs_table = next((i for i in cls.regs if i["name"] == "general"), None)
    if not general_regs_table:
        general_regs_table = {
            "name": "general",
            "descr": "General Registers.",
            "regs": [],
        }
        cls.regs.append(general_regs_table)

    # Add 'VERSION' register if this is the first time we are setting up this core
    # (The register will already be present on subsequent setups)
    if len(cls._setup_purpose) < 2:
        # Auto add 'VERSION' register in 'general' registers table if it doesn't exist
        # If it does exist, give an error
        for reg in general_regs_table["regs"]:
            if reg["name"] == "VERSION":
                raise Exception(
                    cls.name + ": Register 'VERSION' is reserved. Please remove it."
                )
            else:
                general_regs_table["regs"].append(
                    {
                        "name": "VERSION",
                        "type": "R",
                        "n_bits": 16,
                        "rst_val": copy_srcs.version_str_to_digits(cls.version),
                        "addr": -1,
                        "log2n_items": 0,
                        "autoreg": True,
                        "descr": "Product version.  This 16-bit register uses nibbles to represent decimal numbers using their binary values. The two most significant nibbles represent the integral part of the version, and the two least significant nibbles represent the decimal part. For example V12.34 is represented by 0x1234.",
                    }
                )

    # Create an instance of the csr_gen class inside the csr_gen module
    # This instance is only used locally, not affecting status of csr_gen imported in other functions/modules
    csr_gen_obj = csr_gen.csr_gen()
    csr_gen_obj.config = cls.confs
    # Get register table
    reg_table = csr_gen_obj.get_reg_table(cls.regs, cls.rw_overlap, cls.autoaddr)

    return csr_gen_obj, reg_table


def _generate_hw(cls, csr_gen_obj, reg_table):
    """Generate common hardware files"""
    if cls.regs:
        csr_gen_obj.write_hwheader(reg_table, cls.build_dir + "/hardware/src", cls.name)
        csr_gen_obj.write_lparam_header(
            reg_table, cls.build_dir + "/hardware/simulation/src", cls.name
        )
        if not cls.use_netlist:
            csr_gen_obj.write_hwcode(
                reg_table,
                cls.build_dir + "/hardware/src",
                cls.name,
                cls.csr_if,
            )


def _generate_sw(cls, csr_gen_obj, reg_table):
    """Generate common software files"""
    if cls.is_system or cls.regs:
        os.makedirs(cls.build_dir + "/software/src", exist_ok=True)
        if cls.regs:
            csr_gen_obj.write_swheader(
                reg_table, cls.build_dir + "/software/src", cls.name
            )
            csr_gen_obj.write_swcode(
                reg_table, cls.build_dir + "/software/src", cls.name
            )
            csr_gen_obj.write_swheader(
                reg_table, cls.build_dir + "/software/src", cls.name
            )
        config_gen.conf_h(cls.confs, cls.name, cls.build_dir + "/software/src")


def _build_regs_table(cls):
    """Build registers table.
    :returns csr_gen csr_gen_obj: Instance of csr_gen class
    :returns list reg_table: Register table generated by `get_reg_table` method of `csr_gen_obj`
    """
    # Don't create regs table if module does not have regs
    if not cls.regs:
        return None, None

    # Make sure 'general' registers table exists
    general_regs_table = next((i for i in cls.regs if i["name"] == "general"), None)
    if not general_regs_table:
        general_regs_table = {
            "name": "general",
            "descr": "General Registers.",
            "regs": [],
        }
        cls.regs.append(general_regs_table)

    # Add 'VERSION' register if this is the first time we are setting up this core
    # (The register will already be present on subsequent setups)
    if len(cls._setup_purpose) < 2:
        # Auto add 'VERSION' register in 'general' registers table if it doesn't exist
        # If it does exist, give an error
        for reg in general_regs_table["regs"]:
            if reg["name"] == "VERSION":
                raise Exception(
                    cls.name + ": Register 'VERSION' is reserved. Please remove it."
                )
        else:
            general_regs_table["regs"].append(
                {
                    "name": "VERSION",
                    "type": "R",
                    "n_bits": 16,
                    "rst_val": copy_srcs.version_str_to_digits(cls.version),
                    "addr": -1,
                    "log2n_items": 0,
                    "autoreg": True,
                    "descr": "Product version.  This 16-bit register uses nibbles to represent decimal numbers using their binary values. The two most significant nibbles represent the integral part of the version, and the two least significant nibbles represent the decimal part. For example V12.34 is represented by 0x1234.",
                }
            )

    # Create an instance of the csr_gen class inside the csr_gen module
    # This instance is only used locally, not affecting status of csr_gen imported in other functions/modules
    csr_gen_obj = csr_gen.csr_gen()
    csr_gen_obj.config = cls.confs
    # Get register table
    reg_table = csr_gen_obj.get_reg_table(cls.regs, cls.rw_overlap, cls.autoaddr)

    return csr_gen_obj, reg_table


def _generate_hw(cls, csr_gen_obj, reg_table):
    """Generate common hardware files"""
    if cls.regs:
        csr_gen_obj.write_hwheader(reg_table, cls.build_dir + "/hardware/src", cls.name)
        csr_gen_obj.write_lparam_header(
            reg_table, cls.build_dir + "/hardware/simulation/src", cls.name
        )
        if not cls.use_netlist:
            csr_gen_obj.write_hwcode(
                reg_table,
                cls.build_dir + "/hardware/src",
                cls.name,
                cls.csr_if,
            )


def _generate_sw(cls, csr_gen_obj, reg_table):
    """Generate common software files"""
    if cls.is_system or cls.regs:
        os.makedirs(cls.build_dir + "/software/src", exist_ok=True)
        if cls.regs:
            csr_gen_obj.write_swheader(
                reg_table, cls.build_dir + "/software/src", cls.name
            )
            csr_gen_obj.write_swcode(
                reg_table, cls.build_dir + "/software/src", cls.name
            )
            csr_gen_obj.write_swheader(
                reg_table, cls.build_dir + "/software/src", cls.name
            )
            config_gen.conf_h(cls.confs, cls.name, cls.build_dir + "/software/src")


# insert main here
def reg_gen(cls):
    """Generate hw, sw and doc files"""
    csr_gen_obj, reg_table = cls._build_regs_table()
    cls._generate_hw(csr_gen_obj, reg_table)
    cls._generate_sw(csr_gen_obj, reg_table)
    cls._generate_doc(csr_gen_obj, reg_table)
    cls._generate_ipxact(reg_table)
    cls._auto_add_settings()
