ROOT_DIR:=../../../..

BOARD=AES-KU040-DB-G

BOARD_SERVER=$(KU40_SERVER)
BOARD_USER=$(KU40_USER)

#specify any conditions that prevent running this FPGA
NORUN = 0

#DDR controller address width
DDR_ADDR_W=24

include ../vivado.mk

