ROOT_DIR:=../../../..

BOARD_SERVER=$(KU40_SERVER)
BOARD_USER=$(KU40_USER)

DEVICE=xcku040-fbva676-1-c

#specify any conditions that prevent running this FPGA
NORUN = 0

#DDR controller address width
DDR_ADDR_W=24

include ../vivado.mk

